### PR TITLE
Updated gitignores and Cleanup of files

### PR DESCRIPTION
**Pull request by DRSisco**
# Addressed Issue(s)

Offshoot of reviewing code when looking at #179, but not directly related to an issue.

# Goals

Clean up files that should not be in repo due to gitignore/local config.

# Special Considerations

We haven't managed to run this locally due to lack of documentation, so please run locally to check if this doesn't "break" anything.

# Acceptance Criteria

Local Manual Exploratory Black-box integration test.

# Testing

Start up backend/frontend and test using the application.

# Branch

[compileio-cleanup](https://github.com/CompileIO/compile.io/tree/compileio-cleanup)

### CODE REVIEW

**Comment by DRSisco** [comment]
Please test and make sure we didn't break anything!
Things we noticed when looking through https://github.com/CompileIO/compile.io/issues/179#issuecomment-489482100

**Review by ghost — APPROVED** [review]
Looks good, I have been meaning to do this myself, thank you so much for doing this for us. Really appreciate this!

**Comment by DRSisco** [comment]
I was gonna squash it 💔
All good.

**Comment by ghost** [comment]
Sorry about that

**Comment by DRSisco** [comment]
All good. I forgot you guys close other people's PRs. I should've said something :wink: No problems

**Pull request merged**
